### PR TITLE
Use "send to" rather than "send at".

### PR DESCRIPTION
**Pull request by xBorderie**
As reported on Crowdin.

ping @AlexEven and @llandrysg :)

### CODE REVIEW

**Comment by llandrysg** [comment]
Txs Xavier:)

**Comment by xBorderie** [comment]
Thanks @maximebiloe :D

**Comment by Nobodaddy** [comment]
???
I applied the changes once again: https://github.com/PrestaShop/ps_checkpayment/pull/5/commits/f2d4ded3d55e077dfc64afb13ef8628cba739417

**Comment by maximebiloe** [comment]
Thank you!

**Pull request merged**
